#! /bin/bash

# 1.3B model
GLOBAL_BATCH_SIZE=32
NUM_MICRO_BATCH=8
NUM_LAYERS=24
HIDDEN_SIZE=2048
NUM_HEADS=32

LOCAL_BATCH_SIZE=$(expr $GLOBAL_BATCH_SIZE / $NUM_MICRO_BATCH)

TP=4
DP=1
PP=2
MICRO_BATCH_SIZE=$(expr $LOCAL_BATCH_SIZE / $DP)

TP=$TP PP=$PP \
GLOBAL_BATCH_SIZE=$GLOBAL_BATCH_SIZE MICRO_BATCH_SIZE=$MICRO_BATCH_SIZE \
NUM_LAYERS=$NUM_LAYERS HIDDEN_SIZE=$HIDDEN_SIZE NUM_HEADS=$NUM_HEADS \
srun -n 8 -p Big -w nico1 sh examples/pretrain_gpt.sh
